ros_node:
  name: test
  topics:
    publish:
      topic_1:
        name: "cmd_vel"
        type:  "geometry_msgs/Twist"
        middleware_flag: 1
    subscribe:
      topic_1:
        name: "control"
        type:  "std_msgs/String"
        middleware_flag: 1
      topic_2:
        name: "metric"
        type:  "std_msgs/String"
        middleware_flag: 1
      topic_3: 
        name: "manga"
        type:  "geometry_msgs/Twist"
        middleware_flag: 1

